config/routes.rb
Braices::Application.routes.draw do

  devise_for :usuarios

	root :to => "sitio#index"

  match 'anuncios' => 'anuncios#index'
  match 'anuncios/:id/:slug' => 'anuncios#show', :as => 'anuncio'

	namespace :clientes do
		resources :anuncios
	end

end

app/models/anuncio.rb
#encoding:utf-8
class Anuncio < ActiveRecord::Base
	scope :destacados, limit(5).order('id DESC')

  belongs_to :tipo_propiedad
  belongs_to :localidad
  belongs_to :moneda
  belongs_to :tipo_anuncio
  belongs_to :cliente

  has_many :fotos, :dependent => :destroy

  accepts_nested_attributes_for :fotos, :allow_destroy => true

	validates :titulo, :presence => true

  def self.buscar(ubicacion, tipo_anuncio, tipo_propiedad, precio_desde, precio_hasta)

    consulta = ""

    if not ubicacion.blank?
      ubicacion = ubicacion.downcase
      consulta << "lower(localidades.nombre) like '%" << ubicacion << "%' "
      consulta << "or lower(estados.nombre) like '%" << ubicacion << "%' "
      consulta << "or codigo_postal like '%" << ubicacion << "%' "
      consulta << "or lower(direccion) like '%" << ubicacion << "%' "
    end

    #Condición de precios
    if not precio_desde.blank?
      if not consulta.blank?
        consulta << "and "
      end
      consulta << "precio_venta >= " << precio_desde
    end
    
    if not precio_hasta.blank?
      if not consulta.blank?
        consulta << "and "
      end
      consulta << "precio_venta <= " << precio_hasta
    end
    #Fin de condición de precios

    #Condición de tipos de anuncios
    if not tipo_anuncio.blank?
      if not consulta.blank?
        consulta << "and "
      end
      consulta << "tipos_anuncios.nombre = '" << tipo_anuncio << "'"
    end
    #Fin de condición de tipos de anuncios

    #Condición de tipos de propiedades
    if not tipo_propiedad.blank?
      if not consulta.blank?
        consulta << "and "
      end
      consulta << "tipos_propiedades.id = " << tipo_propiedad
    end
    #Fin de condición de tipos de propiedades

    return Anuncio.joins(:tipo_anuncio,:tipo_propiedad, :localidad => :estado).where(consulta)
  end

  private
  before_create do |anuncio|
    anuncio.slug = ("#{anuncio.id} #{anuncio.titulo}").parameterize

    anuncio.fecha_publicacion = Date.current
    anuncio.fecha_vencimiento = Date.current + 30.days

    anuncio.veces_visto = 0
    anuncio.terreno_m2 = anuncio.metros_frente * anuncio.metros_fondo

    anuncio.activo = true
  end

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :localidad
  belongs_to :usuario
  belongs_to :tipo_cliente

  has_many :anuncios
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  belongs_to :pais
	has_many :localidades
end

app/models/foto.rb
class Foto < ActiveRecord::Base
  belongs_to :anuncio
  has_attached_file :foto,
  	:styles => {
  		:peque => "100x100",
  		:mediana => "200x200",
  		:grande => "600x400"
  	}
end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
  belongs_to :estado
end

app/models/moneda.rb
class Moneda < ActiveRecord::Base
end

app/models/pais.rb
class Pais < ActiveRecord::Base
	has_many :estados
end

app/models/propiedad.rb
class Propiedad < ActiveRecord::Base
  belongs_to :tipo_propiedad
	belongs_to :localidad

	validates :direccion, :presence => true
end

app/models/tipo_anuncio.rb
class TipoAnuncio < ActiveRecord::Base
end

app/models/tipo_cliente.rb
class TipoCliente < ActiveRecord::Base
end

app/models/tipo_propiedad.rb
class TipoPropiedad < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController

  def index
    ubicacion = params[:ubicacion]
    tipo_anuncio = params[:tipo_anuncio]
    tipo_propiedad = params[:tipo_propiedad]
    precio_desde = params[:precio_desde]
    precio_hasta = params[:precio_hasta]
	  @anuncios = Anuncio.buscar(ubicacion, tipo_anuncio, tipo_propiedad, precio_desde, precio_hasta)
  end

  def show
  	@anuncio = Anuncio.find(params[:id])
    @anuncio.veces_visto = @anuncio.veces_visto + 1
    @anuncio.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clientes/anuncios_controller.rb
class Clientes::AnunciosController < ApplicationController
  before_filter :authenticate_usuario!
  before_filter :llenar_catalogos, :only => [:new, :create, :edit, :update]

  def index
    @anuncios = Anuncio.all
  end

  def show
    @anuncio = Anuncio.find(params[:id])
  end

  def new
    @anuncio = Anuncio.new
    3.times {@anuncio.fotos.build}
  end

  def create
    @anuncio = Anuncio.new(params[:anuncio])

    if @anuncio.save then
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    @anuncio = Anuncio.find(params[:id])
    3.times {@anuncio.fotos.build}
  end

  def update
    @anuncio = Anuncio.find(params[:id])
    if @anuncio.update_attributes(params[:anuncio])
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    @anuncio = Anuncio.find(params[:id])
    @anuncio.destroy
    redirect_to :action => :index
  end

  private
  def llenar_catalogos
    @tipos_propiedades = TipoPropiedad.all
    @localidades = Localidad.all        
  end

end

app/controllers/sitio_controller.rb
class SitioController < ApplicationController

  def index
    @tipos_propiedades = TipoPropiedad.all
	  @destacados = Anuncio.destacados
  end

end

app/helpers/anuncios_helper.rb
module AnunciosHelper
	include ActionView::Helpers

	def dias_publicado(anuncio)
		tiempo = ((Time.now - anuncio.fecha_publicacion.to_time)/1.day-0.5).to_i
		html = ''
		html << "Publicado hace #{tiempo} dias"
		return html
	end

	def precio(anuncio)
		#<%= number_to_currency @anuncio.precio_venta %>
		cadena = ''
		if anuncio.precio_venta != 0
			cadena << "Venta: " << number_to_currency(anuncio.precio_venta)
		end

		if anuncio.precio_renta != 0
			if not cadena.blank?
				cadena << ", "
			end
			cadena << "Renta: " << number_to_currency(anuncio.precio_renta)
		end
		return cadena
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes/anuncios_helper.rb
module Clientes::AnunciosHelper
end

app/helpers/sitio_helper.rb
module SitioHelper
end

app/views/anuncios/_anuncio.html.haml
%article.span-22.container
  %section
    %h6
      = link_to anuncio.titulo, anuncio_path(anuncio.id, anuncio.slug)
      = number_to_currency anuncio.precio_venta
  %section
    Publicado el #{l anuncio.fecha_publicacion}
  %section
    = anuncio.tipo_anuncio.nombre
  - if not anuncio.cliente.nil? and not anuncio.cliente.tipo_cliente.nil?
    %section
      = anuncio.cliente.tipo_cliente.nombre
  - if not anuncio.localidad.nil? and not anuncio.localidad.estado.nil?
    %section
      = anuncio.localidad.nombre
      , #{anuncio.localidad.estado.nombre}
  %section
    Dirección: #{anuncio.direccion}, C.P. #{anuncio.codigo_postal}
  %section
    = truncate(anuncio.descripcion, :length => 300,    |
      :omission => '...(continua)', :separator => ' ') |

app/views/anuncios/_anuncio_corto.html.haml
%article#anuncio.container.span-22
  %section#titulo
    %h6
      = link_to anuncio.titulo, anuncio_path(anuncio.id, anuncio.slug)
  %section#precio
    = precio(anuncio)
  %section#dias_publicado
    = dias_publicado(anuncio)
  %section#tipo_anuncio
    = anuncio.tipo_anuncio.nombre
  - if not anuncio.cliente.nil? and not anuncio.cliente.tipo_cliente.nil?
    %section#tipo_cliente
      = anuncio.cliente.tipo_cliente.nombre
  - if not anuncio.localidad.nil? and not anuncio.localidad.estado.nil?
    %section#localidad
      = anuncio.localidad.nombre
      , #{anuncio.localidad.estado.nombre}

app/views/anuncios/index.html.haml
%h1 Listado de anuncios
- @anuncios.each do |anuncio|
  %ul#lista_anuncios
    %li
      = render :partial => 'anuncios/anuncio', :locals => {:anuncio => anuncio}

app/views/anuncios/show.html.haml
- content_for :titulo do
  = @anuncio.titulo
- content_for :meta_titulo do
  %meta{:content => @anuncio.titulo, :name => "title"}
%section.span-24
  %ul
    %li
      = link_to 'Regresar al listado', anuncios_path
%article.span-24.container
  %section.span-24
    %h2
      = @anuncio.titulo
      = precio(@anuncio)
    - if not @anuncio.localidad.nil? and not @anuncio.localidad.estado.nil?
      %div
        = @anuncio.localidad.nombre
        , #{@anuncio.localidad.estado.nombre}
    %div
      Publicado el #{l @anuncio.fecha_publicacion}
    %div
      Dirección: #{@anuncio.direccion}
  %section.span-6
    %dl
      %dt Cuartos:
      %dd= @anuncio.num_cuartos
      %dt Baños:
      %dd= @anuncio.num_banios
      %dt Construcción:
      %dd
        = @anuncio.construccion_m2
        m²
      %dt Terreno:
      %dd
        = @anuncio.terreno_m2
        m²
      %dt Año de construcción:
      %dd= @anuncio.anio_construccion
      %dt Tipo de propiedad:
      %dd= @anuncio.tipo_propiedad.nombre
  %section.span-16
    = @anuncio.descripcion
  .span-24
    = @anuncio.veces_visto
    veces visto

app/views/clientes/anuncios/_formulario.html.haml
%p
  = f.label :titulo
  = f.text_field :titulo
%p
  = f.label :descripcion
  = f.text_area :descripcion, :rows => 5, :cols => 40
%p
  = f.label :direccion
  = f.text_area :direccion, :rows => 5, :cols => 40
%p
  = f.label :precio_venta
  = f.number_field :precio_venta, :min=>"1"
%p
  = f.label :precio_renta
  = f.number_field :precio_renta, :min=>"1"
%p
  = f.label :num_cuartos
  = f.number_field :num_cuartos
%p
  = f.label :num_banios
  = f.number_field :num_banios
%p
  = f.label :anio_construccion
  = f.number_field :anio_construccion
%p
  = f.label :tipo_propiedad_id
  = f.collection_select :tipo_propiedad_id, @tipos_propiedades, :id, :nombre, |
    {:include_blank => '[Seleccione un elemento]'}                            |
%p
  = f.label :localidad_id
  = f.collection_select :localidad_id, @localidades, :id, :nombre, |
    {:include_blank => '[Seleccione una opción]'}                  |
%p
  = f.label :metros_frente
  = f.number_field :metros_frente
%p
  = f.label :metros_fondo
  = f.number_field :metros_fondo
%p
  = f.label :caracteristicas
  = f.text_area :caracteristicas, :rows => 5, :cols => 40
= f.fields_for :fotos do |fotos|
  - if fotos.object.new_record?
    %p
      = fotos.label :foto, "Foto"
      = fotos.file_field :foto
= f.fields_for :fotos do |fotos|
  - unless fotos.object.new_record?
    %p
      = link_to image_tag(fotos.object.foto.url(:peque)), |
        fotos.object.foto.url(:original)                  |
      = fotos.check_box :_destroy
%p
  = f.submit "Aceptar"

app/views/clientes/anuncios/create.html.haml
%h1 

app/views/clientes/anuncios/edit.html.haml
%h1 Editar anuncio
%p
  = link_to 'Regresar al listado', clientes_anuncios_path
= form_for @anuncio, :url => clientes_anuncio_path, :html => {:class => "frm_anuncio"} do |f|
  = render :partial => "formulario", :locals => {:f => f}

app/views/clientes/anuncios/index.html.haml
%h1 Listado de anuncios
%p
  = link_to 'Publicar anuncio', new_clientes_anuncio_path
%table
  %thead
    %tr
      %th Título
      %th Fecha de publicación
      %th Fecha de vencimiento
      %th Dirección
      %th Acciones
  %tbody
    - @anuncios.each do |anuncio|
      %tr
        %td
          = anuncio.titulo
        %td
          = l anuncio.fecha_publicacion unless anuncio.fecha_publicacion.nil?
        %td
          = l anuncio.fecha_vencimiento
        %td
          = anuncio.direccion
        %td
          = link_to 'Detalles', clientes_anuncio_path(anuncio)
          = link_to 'Editar', edit_clientes_anuncio_path(anuncio)
          = link_to 'Eliminar', clientes_anuncio_path(anuncio),    |
            :confirm => "¿Seguro que deseas eliminar el anuncio?", |
            :method => :delete                                     |

app/views/clientes/anuncios/new.html.haml
%h1 Publicar anuncio
%p
  = link_to 'Regresar al listado', clientes_anuncios_path
- if @anuncio.errors.any?
  %ul
    - @anuncio.errors.full_messages.each do |msj|
      %li= msj
= form_for @anuncio, :url => clientes_anuncios_path,            |
  :html => {:class => "frm_anuncio", :multipart => true} do |f| |
  = render :partial => "formulario", :locals => {:f => f}

app/views/clientes/anuncios/show.html.haml
%h1= @anuncio.titulo
%p
  = link_to 'Editar anuncio', edit_clientes_anuncio_path(@anuncio)
%article.detalles_anuncio
  %section.anuncio
    %h3 Detalles del anuncio
    %dl
      %dt Descripción:
      %dd= @anuncio.descripcion
      %dt Fecha de publicación:
      %dd= l @anuncio.fecha_publicacion
      %dt Fecha de vencimiento:
      %dd= l @anuncio.fecha_vencimiento
  %section.propiedad
    %h3 Detalles de la propiedad
    %dl
      %dt Dirección:
      %dd= @anuncio.direccion
      %dt Precio de venta:
      %dd= number_to_currency @anuncio.precio_venta
      %dt Precio de renta:
      %dd= number_to_currency @anuncio.precio_renta
      %dt Número de cuartos:
      %dd= @anuncio.num_cuartos
      %dt Número de baños:
      %dd= @anuncio.num_banios
      %dt Construcción (m²):
      %dd= @anuncio.construccion_m2
      %dt Terreno (m²):
      %dd= @anuncio.terreno_m2
      %dt Año de construcción:
      %dd= @anuncio.anio_construccion
      %dt Tipo de propiedad:
      %dd= @anuncio.tipo_propiedad.nombre unless @anuncio.tipo_propiedad.nil?
      %dt Localidad:
      %dd= @anuncio.localidad.nombre unless @anuncio.localidad.nil?
      %dt Características:
      %dd= @anuncio.caracteristicas
  %section.fotos
    %ul
      - @anuncio.fotos.each do |foto|
        %li
          - if not foto.foto.nil?
            = image_tag foto.foto.url(:peque)
%p
  = link_to 'Regresar al listado', clientes_anuncios_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield :titulo
      \- Braices
    = yield :meta_titulo
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #pagina.container
      %header
        #titulo.span-18
          %h2 Portal de Bienes Raices
        #usuario.span-5
          - if usuario_signed_in?
            = current_usuario.email
            = link_to 'Cerrar sesión', destroy_usuario_session_path, :method => :delete
            = link_to 'Mi cuenta', edit_usuario_registration_path
          - else
            = link_to 'Iniciar sesión', new_usuario_session_path
            = link_to 'Registrarme', new_usuario_registration_path
        .clear
      %nav
        %ul
          %li
            = link_to 'Inicio', root_path
          %li
            = link_to 'Anuncios', anuncios_path
          %li
            = link_to 'Publicar anuncio', new_clientes_anuncio_path
      %section#contenido
        - if not notice.blank?
          %p.notice= notice
        - if not alert.blank?
          %p.alert= alert
        = yield
        .clear
      %footer
        Pie de página

app/views/sitio/_formulario_buscar.html.haml
%section#busqueda
  %h3 Buscar anuncios
  = form_tag({:controller => "anuncios", :action => "index"}, :method => "get") do
    %div
      = label_tag :ubicacion, 'Ubicación'
      = text_field_tag :ubicacion, '',                                                          |
        {:class => 'jq_watermark', :placeholder => 'Ciudad, Estado, Dirección o Código postal'} |
    %div
      = label_tag 'tipo_anuncio_venta', 'Venta'
      = radio_button_tag :tipo_anuncio, :Venta, true
      = label_tag 'tipo_anuncio_renta', 'Renta'
      = radio_button_tag :tipo_anuncio, :Renta
    %div
      = label_tag :tipo_propiedad, 'Tipo de propiedad'
      = select_tag :tipo_propiedad,                                          |
        options_from_collection_for_select(@tipos_propiedades, :id, :nombre) |
    %div
      = label_tag :precio, 'Precio'
      = number_field_tag :precio_desde
      a
      \#{number_field_tag :precio_hasta}
    %div
      = submit_tag "Buscar"

app/views/sitio/index.html.haml
- content_for :titulo do
  Página de inicio
%h1 Portal de bienes raices
= render :partial => 'formulario_buscar'
%section
  %h2 Anuncios destacados
  %ul#lista_anuncios
    - @destacados.each do |anuncio|
      %li
        = render :partial => 'anuncios/anuncio_corto', :locals => {:anuncio => anuncio}